let empList=[
{id:'SEL525',name:'NIKHIL T'},
{id:'SEL502',name:'MANIMARAN B'},
{id:'SEL503',name:'BHARATHY'},
{id:'SEL504',name:'KUSUMA N'},
{id:'SEL506',name:'REVATHI C'},
{id:'SEL505',name:'SUMA R'},
{id:'SEL507',name:'KUMARESAN C'},
{id:'SEL508',name:'THANGAPANDI V'},
{id:'SEL524',name:'SATHIYA PRABU'},
{id:'SEL509',name:'SURESH BHARATH'},
{id:'SEL510',name:'ARAVIND R'},
{id:'SEL512',name:'PRABU V'},
{id:'SEL516',name:'OYILA'},
{id:'SEL517',name:'NAGALAKSHMI T'},
{id:'SEL519',name:'SHAKUNTHALA N'},
{id:'SEL529',name:'SARASWATHI G'},
{id:'SEL562',name:'AISHWARYA B C'},
{id:'SEL530',name:'MAHALAKSHMI N'},
{id:'SEL531',name:'JYOTHI P'},
{id:'SEL532',name:'ROSY G'},
{id:'SEL533',name:'GAYITHRI KC'},
{id:'SEL536',name:'ANUPAMA TB'},
{id:'SEL566',name:'JAMUNA A'},
{id:'SEL571',name:'SHRUTHI K T'},
{id:'SEL565',name:'DIVYA SHREE AN'},
{id:'SEL568',name:'MEGHA U'},
{id:'SEL569',name:'MONIKA R'},
{id:'SEL570',name:'PALLAVI SM'},
{id:'SEL567',name:'LAWRENCE Y'},
{id:'SEL563',name:'DEEPA'},
{id:'SEL564',name:'DEEPIKA S'},
{id:'SEL 501',name:'SELVA KUMAR'},
{id:'SEL572',name:'yasotha'}

]